services:
  - type: web
    name: wishlist-bot-sptt-docker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false